/**
 * Base44 backend adapter.
 * Implements the PropertyPulse API surface using @base44/sdk.
 */
import { base44 } from '@/api/base44Client';

export const base44Adapter = {
  auth: {
    me: () => base44.auth.me(),
    updateMe: (profile) => base44.auth.updateMe(profile),
    updateEmail: async () => {
      throw new Error("Email updates require Supabase/Python backend");
    },
    getEmailChangeStatus: async () => ({ email: null, pendingEmail: null }),
    updatePassword: async () => {
      throw new Error("Password updates require Supabase/Python backend");
    },
    logout: (returnUrl) => (returnUrl != null ? base44.auth.logout(returnUrl) : base44.auth.logout()),
    redirectToLogin: (returnUrl) => base44.auth.redirectToLogin(returnUrl ?? window?.location?.href),
  },
  entities: {
    PropertyScore: {
      list: (order = '-created_date') => base44.entities.PropertyScore.list(order),
      create: (data) => base44.entities.PropertyScore.create(data),
      delete: (id) => base44.entities.PropertyScore.delete(id),
    },
    Client: {
      list: (order = '-created_date') => base44.entities.Client.list(order),
      create: (data) => base44.entities.Client.create(data),
      delete: (id) => base44.entities.Client.delete(id),
    },
    PrivateListing: {
      list: (order = '-created_date') => base44.entities.PrivateListing.list(order),
      create: (data) => base44.entities.PrivateListing.create(data),
      delete: (id) => base44.entities.PrivateListing.delete(id),
    },
    Preset: {
      list: () => Promise.resolve([]),
      create: () => Promise.reject(new Error('Presets require Python backend or Supabase')),
      update: () => Promise.reject(new Error('Presets require Python backend or Supabase')),
      delete: () => Promise.reject(new Error('Presets require Python backend or Supabase')),
    },
  },
  property: {
    search: undefined,
    searchByCriteria: () => Promise.resolve({ source: 'public', properties: [] }),
    autoscore: () => Promise.resolve({ scores: {} }),
    placesSearchNearby: () =>
      Promise.reject(new Error('Google Places searchNearby requires Python backend.')),
  },
  integrations: {
    invokeLLM: (options) => base44.integrations.Core.InvokeLLM(options),
    ampUrlBatchGet: () =>
      Promise.reject(new Error('Google AMP URL API requires Python backend (VITE_USE_PYTHON_BACKEND=true).')),
    workspaceDataTransfer: {
      listApplications: () => Promise.reject(new Error('Workspace Data Transfer requires Python backend.')),
      getApplication: () => Promise.reject(new Error('Workspace Data Transfer requires Python backend.')),
      listTransfers: () => Promise.reject(new Error('Workspace Data Transfer requires Python backend.')),
      getTransfer: () => Promise.reject(new Error('Workspace Data Transfer requires Python backend.')),
      createTransfer: () => Promise.reject(new Error('Workspace Data Transfer requires Python backend.')),
    },
    adsense: {
      listAccounts: () => Promise.reject(new Error('AdSense requires Python backend.')),
      getAccount: () => Promise.reject(new Error('AdSense requires Python backend.')),
      listChildAccounts: () => Promise.reject(new Error('AdSense requires Python backend.')),
      listAdClients: () => Promise.reject(new Error('AdSense requires Python backend.')),
      generateReport: () => Promise.reject(new Error('AdSense requires Python backend.')),
      generateReportCsv: () => Promise.reject(new Error('AdSense requires Python backend.')),
      listSites: () => Promise.reject(new Error('AdSense requires Python backend.')),
      listPayments: () => Promise.reject(new Error('AdSense requires Python backend.')),
      listAlerts: () => Promise.reject(new Error('AdSense requires Python backend.')),
    },
    adsensePlatform: {
      listAccounts: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      lookupAccount: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      getAccount: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      createAccount: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      closeAccount: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      createEvent: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      listSites: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      getSite: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      createSite: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      requestSiteReview: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      deleteSite: () => Promise.reject(new Error('AdSense Platform requires Python backend.')),
      transparent: {
        listPlatforms: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
        getPlatform: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
        listGroups: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
        getGroup: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
        patchGroup: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
        listChildSites: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
        getChildSite: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
        patchChildSite: () => Promise.reject(new Error('AdSense Platform transparent requires Python backend.')),
      },
    },
    revenue: {
      adsenseDailySnapshot: () => Promise.reject(new Error('Revenue snapshots require Python backend.')),
      listSnapshots: () => Promise.reject(new Error('Revenue snapshots require Python backend.')),
    },
    analyticsHub: (() => {
      const e = () => Promise.reject(new Error('Analytics Hub requires Python backend.'));
      return {
        listDataExchanges: e,
        getDataExchange: e,
        createDataExchange: e,
        patchDataExchange: e,
        deleteDataExchange: e,
        subscribeDataExchange: e,
        listDataExchangeSubscriptions: e,
        dataExchangeGetIamPolicy: e,
        dataExchangeSetIamPolicy: e,
        dataExchangeTestIamPermissions: e,
        listListings: e,
        getListing: e,
        createListing: e,
        patchListing: e,
        deleteListing: e,
        subscribeListing: e,
        listListingSubscriptions: e,
        listingGetIamPolicy: e,
        listingSetIamPolicy: e,
        listingTestIamPermissions: e,
        listQueryTemplates: e,
        getQueryTemplate: e,
        createQueryTemplate: e,
        patchQueryTemplate: e,
        deleteQueryTemplate: e,
        submitQueryTemplate: e,
        approveQueryTemplate: e,
        listSubscriptions: e,
        getSubscription: e,
        refreshSubscription: e,
        revokeSubscription: e,
        deleteSubscription: e,
        subscriptionGetIamPolicy: e,
        subscriptionSetIamPolicy: e,
        listOrgDataExchanges: e,
      };
    })(),
    androidManagement: (() => {
      const e = () => Promise.reject(new Error('Android Management requires Python backend.'));
      return {
        createSignupUrl: e,
        listEnterprises: e,
        createEnterprise: e,
        getEnterprise: e,
        patchEnterprise: e,
        deleteEnterprise: e,
        generateEnterpriseUpgradeUrl: e,
        createEnrollmentToken: e,
        listEnrollmentTokens: e,
        getEnrollmentToken: e,
        deleteEnrollmentToken: e,
        createWebToken: e,
        listDevices: e,
        getDevice: e,
        patchDevice: e,
        deleteDevice: e,
        issueDeviceCommand: e,
        listDeviceOperations: e,
        getDeviceOperation: e,
        cancelDeviceOperation: e,
        listPolicies: e,
        getPolicy: e,
        patchPolicy: e,
        deletePolicy: e,
        modifyPolicyApplications: e,
        removePolicyApplications: e,
        getApplication: e,
        listWebApps: e,
        createWebApp: e,
        getWebApp: e,
        patchWebApp: e,
        deleteWebApp: e,
        createMigrationToken: e,
        listMigrationTokens: e,
        getMigrationToken: e,
        getProvisioningInfo: e,
      };
    })(),
    googleChat: (() => {
      const e = () => Promise.reject(new Error('Google Chat requires Python backend.'));
      return {
        downloadMedia: e,
        uploadAttachment: e,
        listSpaces: e,
        searchSpaces: e,
        createSpace: e,
        setupSpace: e,
        findDirectMessage: e,
        getSpace: e,
        patchSpace: e,
        deleteSpace: e,
        completeImportSpace: e,
        createMessage: e,
        listMessages: e,
        getMessage: e,
        updateMessage: e,
        patchMessage: e,
        deleteMessage: e,
        getMessageAttachment: e,
        createReaction: e,
        listReactions: e,
        deleteReaction: e,
        listMembers: e,
        getMember: e,
        createMember: e,
        patchMember: e,
        deleteMember: e,
        listSpaceEvents: e,
        getSpaceEvent: e,
        createCustomEmoji: e,
        listCustomEmojis: e,
        getCustomEmoji: e,
        deleteCustomEmoji: e,
        getSpaceReadState: e,
        updateSpaceReadState: e,
        getThreadReadState: e,
        getSpaceNotificationSetting: e,
        patchSpaceNotificationSetting: e,
      };
    })(),
    chromeWebstore: (() => {
      const e = () => Promise.reject(new Error('Chrome Web Store API requires Python backend.'));
      return {
        publishItem: e,
        fetchItemStatus: e,
        cancelSubmission: e,
        setPublishedDeployPercentage: e,
        uploadPackage: e,
      };
    })(),
    dataFusion: (() => {
      const e = () => Promise.reject(new Error('Data Fusion API requires Python backend.'));
      return {
        getLocation: e,
        listLocations: e,
        getOperation: e,
        deleteOperation: e,
        listOperations: e,
        cancelOperation: e,
        listInstances: e,
        createInstance: e,
        getInstance: e,
        patchInstance: e,
        deleteInstance: e,
        restartInstance: e,
        getInstanceIamPolicy: e,
        setInstanceIamPolicy: e,
        testInstanceIamPermissions: e,
        createDnsPeering: e,
        listDnsPeerings: e,
        deleteDnsPeering: e,
        listVersions: e,
      };
    })(),
    dataFusionV1beta1: (() => {
      const e = () => Promise.reject(new Error('Data Fusion API requires Python backend.'));
      return {
        getLocation: e,
        listLocations: e,
        getOperation: e,
        deleteOperation: e,
        listOperations: e,
        cancelOperation: e,
        listInstances: e,
        createInstance: e,
        getInstance: e,
        patchInstance: e,
        deleteInstance: e,
        restartInstance: e,
        getInstanceIamPolicy: e,
        setInstanceIamPolicy: e,
        testInstanceIamPermissions: e,
        createDnsPeering: e,
        listDnsPeerings: e,
        deleteDnsPeering: e,
        listVersions: e,
        upgradeInstance: e,
        removeIamPolicy: e,
        listNamespaces: e,
        getNamespaceIamPolicy: e,
        setNamespaceIamPolicy: e,
        testNamespaceIamPermissions: e,
      };
    })(),
    filestore: (() => {
      const e = () => Promise.reject(new Error('Filestore API requires Python backend.'));
      return {
        getLocation: e,
        listLocations: e,
        getOperation: e,
        deleteOperation: e,
        listOperations: e,
        cancelOperation: e,
        listInstances: e,
        createInstance: e,
        getInstance: e,
        patchInstance: e,
        deleteInstance: e,
        restoreInstance: e,
        revertInstance: e,
        promoteReplica: e,
        pauseReplica: e,
        resumeReplica: e,
        listSnapshots: e,
        getSnapshot: e,
        createSnapshot: e,
        deleteSnapshot: e,
        patchSnapshot: e,
        listBackups: e,
        getBackup: e,
        createBackup: e,
        deleteBackup: e,
        patchBackup: e,
      };
    })(),
    filestoreV1beta1: (() => {
      const e = () => Promise.reject(new Error('Filestore API requires Python backend.'));
      return {
        getLocation: e,
        listLocations: e,
        getOperation: e,
        deleteOperation: e,
        listOperations: e,
        cancelOperation: e,
        listInstances: e,
        createInstance: e,
        getInstance: e,
        patchInstance: e,
        deleteInstance: e,
        restoreInstance: e,
        revertInstance: e,
        promoteReplica: e,
        pauseReplica: e,
        resumeReplica: e,
        listSnapshots: e,
        getSnapshot: e,
        createSnapshot: e,
        deleteSnapshot: e,
        patchSnapshot: e,
        listBackups: e,
        getBackup: e,
        createBackup: e,
        deleteBackup: e,
        patchBackup: e,
        listShares: e,
        getShare: e,
        createShare: e,
        deleteShare: e,
        patchShare: e,
      };
    })(),
    osLogin: (() => {
      const e = () => Promise.reject(new Error('OS Login API requires Python backend.'));
      return {
        signSshPublicKey: e,
        getLoginProfile: e,
        importSshPublicKey: e,
        createSshPublicKey: e,
        getSshPublicKey: e,
        patchSshPublicKey: e,
        deleteSshPublicKey: e,
        provisionPosixAccount: e,
        deletePosixAccount: e,
      };
    })(),
    osLoginV1beta: (() => {
      const e = () => Promise.reject(new Error('OS Login v1beta API requires Python backend.'));
      return {
        signSshPublicKey: e,
        getLoginProfile: e,
        importSshPublicKey: e,
        createSshPublicKey: e,
        getSshPublicKey: e,
        patchSshPublicKey: e,
        deleteSshPublicKey: e,
        provisionPosixAccount: e,
        deletePosixAccount: e,
        signSshPublicKeyUserProjectZone: e,
        signSshPublicKeyUserProjectLocation: e,
      };
    })(),
    translate: (() => {
      const e = () => Promise.reject(new Error('Cloud Translation API v3 requires Python backend.'));
      const names = [
        'projectsRomanizeText',
        'projectsGetSupportedLanguages',
        'projectsTranslateText',
        'projectsDetectLanguage',
        'listLocations',
        'getLocation',
        'batchTranslateText',
        'adaptiveMtTranslate',
        'locationsRomanizeText',
        'locationsGetSupportedLanguages',
        'batchTranslateDocument',
        'locationsTranslateText',
        'translateDocument',
        'refineText',
        'locationsDetectLanguage',
        'getModel',
        'deleteModel',
        'listModels',
        'createModel',
        'listOperations',
        'getOperation',
        'deleteOperation',
        'cancelOperation',
        'waitOperation',
        'importDatasetData',
        'createDataset',
        'listDatasets',
        'getDataset',
        'exportDatasetData',
        'deleteDataset',
        'listDatasetExamples',
        'patchGlossary',
        'getGlossary',
        'deleteGlossary',
        'createGlossary',
        'listGlossaries',
        'deleteGlossaryEntry',
        'getGlossaryEntry',
        'patchGlossaryEntry',
        'listGlossaryEntries',
        'createGlossaryEntry',
        'deleteAdaptiveMtDataset',
        'getAdaptiveMtDataset',
        'createAdaptiveMtDataset',
        'listAdaptiveMtDatasets',
        'importAdaptiveMtFile',
        'listAdaptiveMtSentencesForDataset',
        'deleteAdaptiveMtFile',
        'getAdaptiveMtFile',
        'listAdaptiveMtFiles',
        'listAdaptiveMtSentencesForFile',
      ];
      return Object.fromEntries(names.map((n) => [n, e]));
    })(),
    translateV3beta1: (() => {
      const e = () => Promise.reject(new Error('Cloud Translation API v3beta1 requires Python backend.'));
      const names = [
        'projectsGetSupportedLanguages',
        'projectsTranslateText',
        'projectsDetectLanguage',
        'listLocations',
        'getLocation',
        'batchTranslateText',
        'locationsGetSupportedLanguages',
        'batchTranslateDocument',
        'locationsTranslateText',
        'translateDocument',
        'refineText',
        'locationsDetectLanguage',
        'listOperations',
        'getOperation',
        'deleteOperation',
        'cancelOperation',
        'waitOperation',
        'getGlossary',
        'deleteGlossary',
        'createGlossary',
        'listGlossaries',
      ];
      return Object.fromEntries(names.map((n) => [n, e]));
    })(),
    drive: {
      v3: () => Promise.reject(new Error('Google Drive API v3 requires Python backend.')),
      upload: () => Promise.reject(new Error('Google Drive API v3 requires Python backend.')),
      resumable: () => Promise.reject(new Error('Google Drive API v3 requires Python backend.')),
      v3Raw: () => Promise.reject(new Error('Google Drive API v3 requires Python backend.')),
      uploadRaw: () => Promise.reject(new Error('Google Drive API v3 requires Python backend.')),
      resumableRaw: () => Promise.reject(new Error('Google Drive API v3 requires Python backend.')),
    },
    policyAnalyzer: {
      activitiesQuery: () => Promise.reject(new Error('Policy Analyzer API v1 requires Python backend.')),
    },
    policySimulator: {
      v1: () => Promise.reject(new Error('Policy Simulator API v1 requires Python backend.')),
      v1Raw: () => Promise.reject(new Error('Policy Simulator API v1 requires Python backend.')),
      v1beta: () => Promise.reject(new Error('Policy Simulator API v1beta requires Python backend.')),
      v1betaRaw: () => Promise.reject(new Error('Policy Simulator API v1beta requires Python backend.')),
    },
    doubleclickSearch: {
      v2: () => Promise.reject(new Error('DoubleClick Search API v2 requires Python backend.')),
      v2Raw: () => Promise.reject(new Error('DoubleClick Search API v2 requires Python backend.')),
    },
    saasRuntime: {
      v1: () => Promise.reject(new Error('SaaS Runtime API v1 requires Python backend.')),
      v1Raw: () => Promise.reject(new Error('SaaS Runtime API v1 requires Python backend.')),
      v1beta1: () => Promise.reject(new Error('SaaS Runtime API v1beta1 requires Python backend.')),
      v1beta1Raw: () => Promise.reject(new Error('SaaS Runtime API v1beta1 requires Python backend.')),
    },
    serviceNetworking: {
      v1: () => Promise.reject(new Error('Service Networking API v1 requires Python backend.')),
      v1Raw: () => Promise.reject(new Error('Service Networking API v1 requires Python backend.')),
    },
    dataManager: (() => {
      const e = () => Promise.reject(new Error('Google Data Manager API v1 requires Python backend.'));
      const names = [
        'audienceMembersIngest',
        'audienceMembersRemove',
        'eventsIngest',
        'requestStatusRetrieve',
        'insightsRetrieve',
        'partnerLinksCreate',
        'partnerLinksDelete',
        'partnerLinksSearch',
        'userListDirectLicensesCreate',
        'userListDirectLicensesGet',
        'userListDirectLicensesPatch',
        'userListDirectLicensesList',
        'userListGlobalLicensesCreate',
        'userListGlobalLicensesPatch',
        'userListGlobalLicensesGet',
        'userListGlobalLicensesList',
        'userListGlobalLicenseCustomerInfosList',
        'userListsGet',
        'userListsList',
        'userListsCreate',
        'userListsPatch',
        'userListsDelete',
      ];
      return Object.fromEntries(names.map((n) => [n, e]));
    })(),
  },
  appLogs: {
    logUserInApp: (pageName) => base44.appLogs?.logUserInApp?.(pageName) ?? Promise.resolve(),
  },
  subscription: {
    createCheckoutSession: async (options) => {
      if (typeof base44.integrations?.Stripe?.CreateCheckoutSession === 'function') {
        return base44.integrations.Stripe.CreateCheckoutSession(options);
      }
      const base = typeof window !== 'undefined' ? window.location.origin : '';
      return { url: `${base}/Pricing?checkout=1&plan=${encodeURIComponent(options?.planId || 'premium')}` };
    },
    getPortalUrl: async () => {
      if (typeof base44.integrations?.Stripe?.GetPortalUrl === 'function') {
        return base44.integrations.Stripe.GetPortalUrl();
      }
      const base = typeof window !== 'undefined' ? window.location.origin : '';
      return { url: `${base}/Profile` };
    },
  },
  library: {
    searchRealtors: () => Promise.reject(new Error('Visit library requires Python backend (VITE_USE_PYTHON_BACKEND=true)')),
    listSaved: () => Promise.reject(new Error('Visit library requires Python backend')),
    getSaved: () => Promise.reject(new Error('Visit library requires Python backend')),
    createSaved: () => Promise.reject(new Error('Visit library requires Python backend')),
    updateSaved: () => Promise.reject(new Error('Visit library requires Python backend')),
    deleteSaved: () => Promise.reject(new Error('Visit library requires Python backend')),
    uploadPhoto: () => Promise.reject(new Error('Visit library requires Python backend')),
    deletePhoto: () => Promise.reject(new Error('Visit library requires Python backend')),
    importListingPhotos: () => Promise.reject(new Error('Visit library requires Python backend')),
    shareWithRealtor: () => Promise.reject(new Error('Visit library requires Python backend')),
    listFolders: () => Promise.reject(new Error('Visit library requires Python backend')),
    createFolder: () => Promise.reject(new Error('Visit library requires Python backend')),
    deleteFolder: () => Promise.reject(new Error('Visit library requires Python backend')),
    addToFolder: () => Promise.reject(new Error('Visit library requires Python backend')),
    removeFromFolder: () => Promise.reject(new Error('Visit library requires Python backend')),
    realtorInbox: () => Promise.reject(new Error('Visit library requires Python backend')),
    searchUsers: () => Promise.reject(new Error('Visit library requires Python backend')),
    createPeerShare: () => Promise.reject(new Error('Visit library requires Python backend')),
    deletePeerShare: () => Promise.reject(new Error('Visit library requires Python backend')),
    sharedWithMe: () => Promise.reject(new Error('Visit library requires Python backend')),
    peerSharesOutgoing: () => Promise.reject(new Error('Visit library requires Python backend')),
  },
  projects: {
    limits: () => Promise.reject(new Error('Projects require Python backend')),
    validateCompare: () => Promise.reject(new Error('Projects require Python backend')),
    list: () => Promise.reject(new Error('Projects require Python backend')),
    listInvites: () => Promise.reject(new Error('Projects require Python backend')),
    create: () => Promise.reject(new Error('Projects require Python backend')),
    get: () => Promise.reject(new Error('Projects require Python backend')),
    update: () => Promise.reject(new Error('Projects require Python backend')),
    delete: () => Promise.reject(new Error('Projects require Python backend')),
    inviteMember: () => Promise.reject(new Error('Projects require Python backend')),
    acceptInvite: () => Promise.reject(new Error('Projects require Python backend')),
    declineInvite: () => Promise.reject(new Error('Projects require Python backend')),
    removeMember: () => Promise.reject(new Error('Projects require Python backend')),
    addProperty: () => Promise.reject(new Error('Projects require Python backend')),
    addProperties: () => Promise.reject(new Error('Projects require Python backend')),
    removeProperty: () => Promise.reject(new Error('Projects require Python backend')),
    rescore: () => Promise.reject(new Error('Projects require Python backend')),
  },
  contacts: {
    search: () => Promise.reject(new Error('Contacts require Python backend')),
    list: () => Promise.reject(new Error('Contacts require Python backend')),
    add: () => Promise.reject(new Error('Contacts require Python backend')),
    accept: () => Promise.reject(new Error('Contacts require Python backend')),
    decline: () => Promise.reject(new Error('Contacts require Python backend')),
    update: () => Promise.reject(new Error('Contacts require Python backend')),
    remove: () => Promise.reject(new Error('Contacts require Python backend')),
  },
  shares: {
    send: () => Promise.reject(new Error('Property shares require Python backend')),
    inbox: () => Promise.reject(new Error('Property shares require Python backend')),
    sent: () => Promise.reject(new Error('Property shares require Python backend')),
    pendingCount: () => Promise.resolve({ count: 0 }),
    clientReport: () => Promise.reject(new Error('Property shares require Python backend')),
    get: () => Promise.reject(new Error('Property shares require Python backend')),
    markViewed: () => Promise.reject(new Error('Property shares require Python backend')),
    returnScores: () => Promise.reject(new Error('Property shares require Python backend')),
    cancel: () => Promise.reject(new Error('Property shares require Python backend')),
  },
  invitations: {
    send: () => Promise.reject(new Error('Invitations require Python backend')),
    validateToken: () => Promise.reject(new Error('Invitations require Python backend')),
    accept: () => Promise.reject(new Error('Invitations require Python backend')),
    listSent: () => Promise.reject(new Error('Invitations require Python backend')),
  },
  referrals: {
    me: () => Promise.reject(new Error('Referrals require Python backend')),
    validate: () => Promise.reject(new Error('Referrals require Python backend')),
    claim: () => Promise.reject(new Error('Referrals require Python backend')),
  },
  preferenceCards: {
    preview: () => Promise.reject(new Error('Preference cards require Python backend')),
    enableShare: () => Promise.reject(new Error('Preference cards require Python backend')),
    updateShare: () => Promise.reject(new Error('Preference cards require Python backend')),
    regenerate: () => Promise.reject(new Error('Preference cards require Python backend')),
    revokeShare: () => Promise.reject(new Error('Preference cards require Python backend')),
    getPublic: () => Promise.reject(new Error('Preference cards require Python backend')),
  },
  support: {
    submitFeedback: () =>
      Promise.reject(new Error('In-app feedback requires the Python API (VITE_USE_PYTHON_BACKEND=true).')),
  },
};
